### ISSUE TITLE
분산 추적

### ISSUE THREAD

**Issue by Jake-huen** [CCCloudPlatform/Heart#10]
## 기능 설명
마이크로서비스에서 분산추적을 위해 Zipkin과 Spring Cloud Sleuth를 사용

### 작업 상세 내용
- [x] UserService, API GW에 Zipkin 설정
- [x] API Request Test 및 결과 확인

### 참고할만한 자료
https://engineering.linecorp.com/ko/blog/line-ads-msa-opentracing-zipkin

**Comment by KwonSunJae** [comment]
특별한 추가내용이 없어 해당 이슈는 닫도록 하겠습니다. 

추후, Observing과 관련된 시각화는 또다른 이슈를 열어 관리 하도록 하겠습니다.

수고하셨습니다!
