### ISSUE TITLE
서비스 확장을 위한 프로젝트 기여 환경 구축

### ISSUE THREAD

**Issue by KwonSunJae** [CCCloudPlatform/Heart#8]
앞으로 더 많은 사람들이 해당 프로젝트에 기여를 시작할 것 같습니다.

이제는 명확한 Guide Line을 제시해 
프로젝트 기여에 있어 혼선을 방지하고, 
체계를 구체적으로 확장해나갔으면 좋겠습니다.

단순히,

1 Issue -> 1 feature 보다 더 명확하게 

1. 이슈 템플릿 제공
2. PR 템플릿 제공
3. TEST 가이드 라인 제공
4. Git Branch 전략 

등등 다양한 세부적인 것들을 이제는 명확히 해야할 때가 온것 같습니다.

**Comment by tjdgns8439** [comment]
동의합니다. TEST 가이드라인 같은 경우 참고할만한 레퍼런스가 있을까요?

**Comment by zzu-yaaa** [comment]
저의 작은 의견 남기고 갑니다!
1 Issue -> 1 feature은 유지하되, 템플릿을 통해서 명확하게 작성하면 좋을 것 같습니당

1. 이슈 템플릿
```
# 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

## 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 참고할만한 자료(선택)

``` 

2. PR 템플릿
```
## 연관된 이슈

> ex) #이슈번호

## 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 결과 (선택)

> 결과 스크린샷 또는 개인 노션 링크 임베드

## 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분
> 질문
> 공유하고 싶은 내용 등 자유롭게 작성 ~
``` 

3. 프로젝트를 진행하면서 테스트 코드를 올바르게 작성해본적이 없어 패스하겠습니다,,

4. Git Branch 전략

feature > develop > main
- 현재 디벨롭 브랜치가 존재하나, 메인 브랜치로부터 분기하여 작업하고 있는 것으로 보여 해당 내용에 대한 논의가 필요해보입니다!

feature 브랜치명
- 현행 유지해도 좋을 것 같습니다
- {prefix}/{issue-number}
- ex) feat/6, fix/37

**Comment by KwonSunJae** [comment]
Thank you @zzu-yaaa  !! LGTM
